End-to-end-provenance/RDataTracker

- R/RDataTracker.R
> Changed the value stored for file nodes.

- DESCRIPTION
> fixes issues #220 #224

- R/RDataTracker.R
> Moved some code from ddg.run to ddg.init so it is used in console mode.

- .travis.yml
- R/DDGCheckpoint.R
- R/DDGStatement.R
- R/RDataTracker.R
- README.md
- travis-linter.sh
As discussed this morning, Travis CI integration for RDataTracker.
- at the moment run lintR (static analysis tools for R).
I will add support for regression test once they have been updated.
Once this pull request is accepted, the test should start to run automatically.
> Travis integration + LintR

- R/RDataTracker.R
I made changes as I suggested in #267 and #268.
If merged it could allow Caroline to move forward while we finalise the format.
> Showcasing my suggestion for Elizabeth

- R/RDataTracker.R
Fixed the bugs that popped up after pull request #269 . It should be working now!
I think that the DDGExplorer parser needs to be fixed because of the changes in the `.txt` and `.json` files. It's on my todo list.
> Fixed bugs regarding ValType

- tests.xml
- tests/DDGStatementTest/sourceTest.r
The test run cmp and fail in case the files are not identical.
Based on today discussion, it is ready to be merged.
> Updated test to do cmp at the end

- tests.xml
- tests/DDGStatementTest/sourceTest.r
- tests/HFDatasetPreview/expected_HFDatasetPreview.out
- tests/HFDatasetPreview/expected_HFDatasetPreview_ddg.json
- tests/HFDatasetPreview/expected_HFDatasetPreview_ddg.txt
- tests/NoDevOffTest/expected_NoDevOffTest.out
- tests/NoDevOffTest/expected_NoDevOffTest_ddg.json
Fixed the problem in the development branch where if there is a difference in the `.json` files but not the `.out` files, the tests will not fail.
> fixed error with automatic tests not failing when it should

- R/RDataTracker.R
- tests/ReturnTest/ReturnTest.R
- tests/ReturnTest/expected_ReturnTest.out
- tests/ReturnTest/expected_ReturnTest_ddg.json
I tested what happens if a for loop is the last line of a function.  One of the tests failed but had an easy fix, which is what this one is.  I created issues for the other cases that failed.
> Last func statement

- R/DDGStatement.R
- R/DataNodes.R
- R/Functions.R
- R/ProcNodes.R
- R/RDataTracker.R
- R/Utilities.R
Moving things out of RDataTracker.R to more sensible files.
> Refactoring

- R/OutputJSON.R
> Added more detail to the OS attribute in the environment

- .travis.yml
- R/DataNodes.R
- R/IOTrace.R
Calculating the data value to save for a data frame with 1 row gave an
error.
IO tracing for writing to files did not work when run in console mode.
> Fixed 2 bugs

- R/API_core.R
- R/API_rdt.R
- R/Annotation_rdt.R
- R/OutputJSON.R
- R/Utilities.R
Updated to work with current versions of devtools and roxygen2.
> Travis bug

- scriptTests/NoDetails/.gitignore
- scriptTests/NoDetails/NoDetails.R
- scriptTests/NoDetails/rdt/.gitignore
- scriptTests/NoDetails/rdt/expected_prov.json
- scriptTests/NoDetails/rdt/expected_test.out
- scriptTests/NoDetails/rdtLite/.gitignore
- scriptTests/NoDetails/rdtLite/expected_prov.json
- scriptTests/NoDetails/rdtLite/expected_test.out
- scriptTests/sourceTest.r
- tests.xml
This is testing the new details option in `prov.run`, when `details = FALSE`. All other tests have `details = TRUE`. `tests.xml` and `sourceTest.r` has been changed to enable passing in such parameters for testing.
> NoDetails test (when details = FALSE)

- DESCRIPTION_rdt
- DESCRIPTION_rdtLite
- NEWS_rdt.md
- NEWS_rdtLite.md
- R/IOTrace.R
- scriptTests/SourceFunc/rdt/expected_prov.json
- scriptTests/SourceFunc/rdt/expected_test.out
They were showing up as input files.
> Moved sourced scripts to the sourced script list

- scriptTests/CalculateSqrt/.gitignore
- scriptTests/FileNodes/FileNodes.R
- scriptTests/FileNodes/rdt/expected_prov.json
- scriptTests/FileNodes/rdt/expected_test.out
- scriptTests/FileNodes/rdtLite/expected_prov.json
- scriptTests/FileNodes/rdtLite/expected_test.out
- scriptTests/basic/.gitignore
For the URL test, using a test.html file we have control over so we know
it will not change.
> Changed FileNodes test.

- scriptTests/AssignOperators/AssignOperators.R
- scriptTests/AssignOperators/rdt/expected_prov.json
- scriptTests/AssignOperators/rdt/expected_test.out
- scriptTests/AssignOperators/rdtLite/expected_prov.json
- scriptTests/AssignOperators/rdtLite/expected_test.out
Uncommented 2 tests that work on rdtLite.
> Assignment Operators Test

- R/IOTrace.R
- scriptTests/DataFunction/DataFunction.R
- scriptTests/DataFunction/rdt/.gitignore
- scriptTests/DataFunction/rdt/data/pets.csv
- scriptTests/DataFunction/rdt/expected_prov.json
- scriptTests/DataFunction/rdt/expected_test.out
- scriptTests/DataFunction/rdtLite/.gitignore
- scriptTests/DataFunction/rdtLite/data/pets.csv
- scriptTests/DataFunction/rdtLite/expected_prov.json
- scriptTests/DataFunction/rdtLite/expected_test.out
- scriptTests/NoDetails/rdt/expected_prov.json
- scriptTests/NoDetails/rdtLite/expected_prov.json
- scriptTests/NoDevOff/rdt/expected_test.out
- scriptTests/NoDevOff/rdtLite/expected_prov.json
- scriptTests/NoDevOff/rdtLite/expected_test.out
- scriptTests/Plot1/rdt/expected_prov.json
- scriptTests/Plot1/rdt/expected_test.out
- scriptTests/Plot1/rdtLite/expected_prov.json
- scriptTests/Plot1/rdtLite/expected_test.out
- scriptTests/RMarkdown/rdt/expected_prov.json
- scriptTests/RMarkdown/rdt/expected_test.out
- scriptTests/RMarkdown/rdtLite/expected_prov.json
- scriptTests/RMarkdown/rdtLite/expected_test.out
- tests.xml
Creates output nodes for calls to R's data function to hold the datasets
that are loaded in.
> Fixes issue 553

- R/DataNodes.R
- scriptTests/AssignOperators/rdt/expected_prov.json
- scriptTests/AssignOperators/rdt/expected_test.out
- scriptTests/AssignOperators/rdtLite/expected_prov.json
- scriptTests/AssignOperators/rdtLite/expected_test.out
- scriptTests/DataType/DataType.R
- scriptTests/DataType/rdt/expected_prov.json
- scriptTests/DataType/rdt/expected_test.out
- scriptTests/DataType/rdtLite/expected_prov.json
- scriptTests/DataType/rdtLite/expected_test.out
- scriptTests/OddParameter/rdt/expected_prov.json
- scriptTests/OddParameter/rdt/expected_test.out
- tests.xml
A data node for an environment uses the names of the variables in the
environment as its value.
> Record the names of variables in an environment

- scriptTests/FileNodes/FileNodes.R
- scriptTests/FileNodes/rdt/expected_prov.json
- scriptTests/FileNodes/rdt/expected_test.out
- scriptTests/FileNodes/rdtLite/expected_prov.json
- scriptTests/FileNodes/rdtLite/expected_test.out
Trying a command in the pipe() test that should hopefully work the same
on Unix and Windows.
> Changed FileNodes test

- scriptTests/basic/rdtLite/expected_prov.json
- scriptTests/fromEnv/rdtLite/expected_prov.json
- scriptTests/fromEnv/rdtLite/expected_test.out
- tests.xml
Needs to look for the expected results in prov_console rather than a
directory named after the script.
> Fixed tests.xml update task for tests run in console mode.

- R/API_core.R
- R/OutputJSON.R
- R/SourcedScripts.R
> Store "console" in the script table.

- R/API_core.R
- R/OutputJSON.R
- R/SourcedScripts.R
If run in console mode, the commands are collected into a script called
console.R stored in the scripts folder.  The path to this file now shows
up as the main script in the JSON file.
> Use path to console.R in scripts folder when creating JSON.

- .travis-rdt.yml
- .travis-rdtLite.yml
Commands to install packages had been commented out.
> Updated travis.yml files for the separate builds.
