End-to-end-provenance/RDataTracker

R/DDGCheckpoint.R
`R CMD check` passes after removing this call
This was causing #60 (i.e. `install_github("dlebauer/RDataTracker@patch-1")` now works
=> remove `library(RDataTracker)` from source

NAMESPACE, R/RDataTracker.R
- ddg.display.ddg() is now simply ddg.display();
- starting DDG-Explorer does not block the use of RStudio anymore (user can go back and forth);
=> Implement Margo's fix + ddg.display.dgg() -> ddg.display()

DESCRIPTION, R/RDataTracker.R, man/InitSave.Rd
A new parameter (save.debug=FALSE) was added to ddg.run and ddg.save to optionally save a series of files to the debug directory for troubleshooting.  These files include copies of the various lookup tables (nodes, edges, etc) as well as annotated versions of the main script and any sourced scripts.  In earlier versions of RDataTracker, these files were saved by default.  These changes address issue #156.
=> Add option to save debug files

NAMESPACE, R/RDataTracker.R, test-no-instrumentation.xml
Changed the syntax used to put an S4 object into a list to avoid the error described in issue 165.
Updated NAMESPACE since R now expects explicit import statements for items used from base packages.
Also, removed SivanSamplingSmaller from the tests that are run with test-all.  The script itself no longer runs even without RDataTracker because of the way that it uses lists of S4 objects.
=> Fixes #165

NAMESPACE
Commented out the importFrom lines that cause RStudio on Windows to
crash.  Leaving out these lines result in a note when we run cran check,
but leaving them in causes R to crash inside RStudio on Windows.
This is issue 116 again.  I recently added these importFrom lines after running cran check, forgetting about this bug.  Now, I kept the lines in NAMESPACE but they are commented out with an explanation of the bug.
=> Fixed RStudio on Windows crashing problem

R/RDataTracker.R, examples-no-instrumentation/ControlConstructTest/ddg/.gitignore
Fixes issue 63 in the DDG Explorer repository.  The wrong path was being stored in the ddg.
=> Fixed file path for snapshot nodes.

R/RDataTracker.R
There was an extra comman in the json output after the SourcedScripts
attribute in the case that there actually were sourced scripts.
=> Fixed issue #222

.travis.yml, tests/depends.r
Travis has been modified to  not run CRAN check (so will not fell because the package does not meet CRAN standards).
It now runs the following:
```
- R CMD build .
- R CMD check *tar.gz
- ant -file build.xml install
- ant -file tests.xml basicTest
- ant -file tests.xml test-all
```
Ready to be merged as far travis test is concerned.
However, not that tests.xml usefulness in this context is limited, as the failure on test condition not being met does not seem to be implemented.
Extract of output:
```
basicTest:
run-regression-test:
run-test:
[mkdir] Created dir: /home/travis/build/tfjmp/RDataTracker/tests/basicTest/local
[copy] Copying 1 file to /home/travis/build/tfjmp/RDataTracker/tests/basicTest
[exec] Result: 1
[copy] Copying 4 files to …
```
=> No more CRAN check (as it does not seem anyone plan to make it work), run `ant -file tests.xml test-all`

NAMESPACE, R/DDGStatement.R, R/RDataTracker.R, man/InitSave.Rd, tests/SourceFuncTest/expected_SourceFuncTest.out, tests/SourceFuncTest/expected_SourceFuncTest_ddg.json, tests/SourceFuncTest/source3.r, tests/SourceFuncTest/source4.r
ddg.annotate.on and off were not working since the introduction of the DDGStatement class.  That is now fixed.  In addition, they can now be used to turn annotation of individual functions on and off dynamically.
=> Annotate func on off

R/RDataTracker.R, tests.xml, tests/AnnotateOnOffTest/.gitignore, tests/AnnotateOnOffTest/AnnotateOnOffTest.R, tests/AnnotateOnOffTest/expected_AnnotateOnOffTest.out, tests/AnnotateOnOffTest/expected_AnnotateOnOffTest_ddg.json
This tests the ddg.annotate.on and ddg.annotate.off functions.
Also, fixed the behavior when these functions are passed a vector of
function names instead of just a single name.
=> Added AnnotateOnOffTest to regression suite

.travis.yml, tests.xml, tests/ProvJsonTest/ProvJsonTest.r, tests/ProvJsonTest/cases/empty.json, tests/ProvJsonTest/cases/fail1.json, tests/ProvJsonTest/cases/pass1.json, tests/ProvJsonTest/complianceTest.r, tests/ProvJsonTest/schema.json
Prov-Json compliance testing is run on each test before edits to the files are made before the diff check. This done in the target `prov-json-compliance-test`. 
Additionally, when the ant targets `test-all` and `test-travis` are run, the test, `ProvJsonTest`, will run before `basicTest`. This is a short test that runs the `json_validate` function of the package `jsonvalidate` on cases where it is and it is not compliant, to make sure that the results are as expected.
When using the target `test-travis`, the build will fail if the above tests fail.
=> Automatic prov-json compliance checking in regression tests.

R/Functions.R, R/ProcNodes.R, R/RDataTracker.R, R/ReturnValues.R
Changed return value type from .ddg.get.matching.return.value.nodes to
be a vector instead of a data frame.
Changed where .ddg.add.to.function.table is called to reduce the amount
of parameter passing required.
=> Refactoring

.Rbuildignore, .travis-rdt.yml, .travis-rdtLite.yml, .travis.yml, R/Functions.R, R/FunctionsDefined.R, R/ProcNodes.R, R/Utilities.R, scriptTests/FileNodes/rdt/expected_prov.json, scriptTests/FileNodes/rdt/expected_test.out, scriptTests/FileNodes/rdtLite/expected_prov.json, scriptTests/FileNodes/rdtLite/expected_test.out
New cran checks produced warnings when our examples were run.  The problem was that we were using is.null and is.na to check whether a variable was null or NA.  In the case that the value contained a vector, these functions return a vector of logical values, instead of a single logical value.  This caused a warning when a single logical value was expected.
With R 3.6, the cran checks began looking for this problem.
=> Cleaned up is.null and is.na calls.

R/IOTrace.R, scriptTests/SourceFunc/rdtLite/expected_prov.json, scriptTests/SourceFunc/rdtLite/expected_test.out
Depending on how the script is run, the source function uses readLines
to read in the script (RStudio) or not (Rscript).  When readLines was
not used, the sourced script information was not being captured.
=> Fixed bug in capturing sourced scripts

R/RDataTracker_core.R
If called from debug.init, we now start the search for variables in the
stack frame above debug.init.
=> Fixed issue #444

.gitignore, R/DataNodes.R, R/Edges.R, scriptTests/AssignOperators/AssignOperators.R, scriptTests/AssignOperators/rdt/expected_prov.json, scriptTests/AssignOperators/rdt/expected_test.out, scriptTests/AssignOperators/rdtLite/expected_prov.json, scriptTests/AssignOperators/rdtLite/expected_test.out, scriptTests/CalculateSqrt/rdtLite/expected_prov.json, scriptTests/CalculateSqrt/rdtLite/expected_test.out, scriptTests/HFDatasetPreview/rdt/expected_prov.json, scriptTests/HFDatasetPreview/rdt/expected_test.out, scriptTests/HFDatasetPreview/rdtLite/expected_prov.json, scriptTests/HFDatasetPreview/rdtLite/expected_test.out, scriptTests/NoDevOff/rdt/expected_prov.json, scriptTests/NoDevOff/rdt/expected_test.out, scriptTests/NoDevOff/rdtLite/expected_prov.json, scriptTests/NoDevOff/rdtLite/expected_test.out, scriptTests/Plot1/rdt/expected_prov.json, scriptTests/Plot1/rdt/expected_test.out, scriptTests/Plot1/rdtLite/expected_prov.json, scriptTests/Plot1/rdtLite/expected_test.out, scriptTests/RMarkdown/rdt/expected_prov.json, scriptTests/RMarkdown/rdt/expected_test.out, scriptTests/RMarkdown/rdtLite/expected_prov.json, scriptTests/RMarkdown/rdtLite/expected_test.out, scriptTests/SourceFunc/rdtLite/expected_prov.json, scriptTests/SourceFunc/rdtLite/expected_test.out, scriptTests/ddgDeepNesting/rdtLite/expected_prov.json, scriptTests/ddgDeepNesting/rdtLite/expected_test.out
Prevents confusion between what is in the global environment when a
statement is executed compared to what was in the global environment
when the script started.
=> Fixes issue 551

R/DataNodes.R, R/RDataTracker_core.R, scriptTests/AssignOperators/AssignOperators.R, scriptTests/AssignOperators/rdt/expected_prov.json, scriptTests/AssignOperators/rdt/expected_test.out, scriptTests/AssignOperators/rdtLite/expected_prov.json, scriptTests/AssignOperators/rdtLite/expected_test.out
When an inner function does a non-local, non-global assignment, rdtLite
no longer attempts to create a data node for it.  Trying to do so
resulted in an error since the variable could not be found in the global
scope, which is the only scope rdtLite has access to.
Also, rdt creates the correct nodes and edges in this case.
=> Fixes issue 550

tests.xml
This happens for test-travis and test-all but not individual tests, to
avoid seeing the version number repeatedly output with each test.
=> Added output of ant and java versions when tests are run

.travis-rdtLite.yml
rmarkdown was misspelled, preventing the tests from running on Travis.
=> Fixed typo in .travis-rdtLite.yml

tests/testthat/testAPI.R
It was too hard to get a test that worked on all platforms.
=> Deleted the test where a specific directory is passed in

R/RDataTracker_core.R
If the call string to include in the warning was more than one line
long, there was a warning while creating the warning node.
Fixes issue #604
=> Fixed bug when creating warning nodes

DESCRIPTION_rdt, DESCRIPTION_rdtLite, R/IOTrace.R, R/RDataTracker_core.R
We only use it for tracing the files it produces.  If a user does not
otherwise need ggplot2, they should have to install it.  It now checks
if it is installed before setting up the tracing.
=> Changed ggplot2 from a required package to a suggested package
